### PR TITLE
Add confirmation modal to overwrite a file by upload

### LINKED ISSUE #232: [FEATURE REQUEST] Allow file rewrite for PrusaLink uploads
When I try to reupload a file that already exists on the flashdrive, I currently get an error (403 iirc?). PrusaLink on MK3+RPi does not do that and rewrites the file instead. I find that very useful because it allows me to restart prints (after first-layer problems etc.) by just re-"upload and print" directly from PrusaSlicer instead of opening the PrusaLink in a browser and searching for the right file to start.

So would it be please possible to implement that on the Mini too?
- automatically rewrite already existing file if a file with the same name is uploaded.

### PR DESCRIPTION
**Pull request by Lowentwickler**
Snímek obrazovky z 2023-04-19 09-54-32

Closes #232

### CODE REVIEW

**Review by tomashusakk — CHANGES_REQUESTED** [review]
dotaz vyskočí pokaždé, ikdyž soubor na tiskárně není

**Comment by Lowentwickler** [comment]
> dotaz vyskočí pokaždé, ikdyž soubor na tiskárně není

Should be resolved by https://github.com/prusa3d/Prusa-Link/pull/762

**Review by tomashusakk — APPROVED** [review]

**Comment by narfotic** [comment]
Is it possible to also add this to PrusaSlicer? I always use the 'Send to printer'-button but I get that error all the time. And no way to go around it but publish again and add a letter in the filename...

**Comment by Madblam** [comment]
Same issue here. I click sent to printer only to come back two hours laters to notice there was already a file with the same name.

**Pull request merged**
